### ISSUE TITLE
Update docs to use IBM Cloud CLI instead of Softlayer

### ISSUE THREAD

**Issue by psschwei** [ibm-cloud-docs/FileStorage#10]
Some of the Ordering File Storage docs use the Softlayer CLI instead of the IBM Cloud CLI for working via the command line. Ideally, these would be updated to use the IBM Cloud CLI.

Pages in question:
* https://cloud.ibm.com/docs/FileStorage?topic=FileStorage-orderingSLCLI
* https://cloud.ibm.com/docs/FileStorage?topic=FileStorage-ordering-snapshots#ordering-snapshot-space-through-the-slcli

**Comment by vickmuir** [comment]
The issue has been recorded in JIRA (DOCS-6226).
