### ISSUE TITLE
Incorrect inode information on FAQ page

### ISSUE THREAD

**Issue by chwazik** [ibm-cloud-docs/FileStorage#11]
On https://cloud.ibm.com/docs/FileStorage?topic=FileStorage-file-storage-faqs:

- How many files/directories are allowed for specific file volume sizes? What is the maximum number of inodes allowed per volume size?

    The table showing maximum inodes for volume sizes does not appear correct. I have a 150GB SoftLayer NFS volume that has 5,291,935 inodes. The comparison table indicates that the max for that size is 3,112,863.

- Can I increase inodes for my NFS volume?

    The answer to this question states that increasing inodes after a volume is expanded is a manual step and requires a support ticket. I've found that increasing a volume's size also increases the number of inodes available. The same 150GB volume referenced above was originally provisioned as a 100GB volume, which had 3,735,449 inodes. After increasing it to 150GB, inodes increased to 5,291,935.

**Comment by vickmuir** [comment]
Thank you for the feedback.

**Comment by vickmuir** [comment]
The FAQs have been updated.
