### ISSUE TITLE
Throughput value is incorrect.

### ISSUE THREAD

**Issue by ytama** [ibm-cloud-docs/FileStorage#12]
Hello,
https://cloud.ibm.com/docs/FileStorage?topic=FileStorage-getting-started&locale=en#block-size

In Table 1, I think the Throughput values for 4KB Block size and 8KB Block size are incorrect.

When the block size is 4KB and 1,000 IOPS, the throughput is 4MB / s, and when the block size is 8KB and 1,000 IOPS, the throughput is 8MB / s.
Could you check it?
Thank you,

**Comment by vickmuir** [comment]
Fixed.
