### ISSUE TITLE
Clear hint missing not to use NFS 4.1

### ISSUE THREAD

**Issue by tschrenk-corp** [ibm-cloud-docs/FileStorage#14]
Due tro a current customer issue (Condor) CS2312730 I would suggest to clearly state NOT to to use NFS 4.1

and put the following sennce in bold

Both NFSv3 and NFSv4.1 are supported in the IBM Cloud® environment. However, the use NFSv3 is preferred. Because NFSv4.1 is a stateful protocol (not stateless like NFSv3), protocol issues can occur during network events. NFSv4.1 must quiesce all operations and then complete lock reclamation. While these operations are taking place, disruptions can occur.

**Comment by vickmuir** [comment]
Thank you for your feedback. I have brought it to the attention of the Product Manager.
