### ISSUE TITLE
IOPS at 4KB and 8KB is incorrect. 

### ISSUE THREAD

**Issue by ytama** [ibm-cloud-docs/FileStorage#15]
Hello,
The example in Table 1 illustrates storage with 1,000 IOPS performance when reading and writing at 16KB.
When the block size is 4KB and 8KB, IOPS can only be up to 1,000, so throughput will be 4MB and 8MB.

https://cloud.ibm.com/docs/FileStorage?topic=FileStorage-getting-started
https://cloud.ibm.com/docs/BlockStorage?topic=BlockStorage-getting-started

Best,

**Comment by vickmuir** [comment]
Thank you for your feedback.
