### ISSUE TITLE
Modify: How many instances can share the use of a provisioned File Storage for Classic volume?

### ISSUE THREAD

**Issue by gaskinner84** [ibm-cloud-docs/FileStorage#17]
https://cloud.ibm.com/docs/FileStorage?topic=FileStorage-file-storage-faqs#authlimit

Can we change the wording of this so customers understand that authorization limits include hosts, subnets and IPs? Also, I have changed Sales to Support, as ACS does this.

Current wording:

The default limit for number of authorizations per file volume is 64. To increase this limit, contact your sales representative.

Suggested wording: 

The default limit for number of authorizations per file volume is 64. This includes subnet, host and IP authorizations(or a combination to total 64). To increase this limit, contact your **Support** representative.

Regards,

Gary S.
Storage Support Lead
IBM Cloud Support

**Comment by vickmuir** [comment]
Transferred work item to https://jira.softlayer.local/browse/DOCS-7082.
