### ISSUE TITLE
Please update with the pricing of Snapshot and Replication

### ISSUE THREAD

**Issue by khayama-zz** [ibm-cloud-docs/FileStorage#2]
The user can see the basic volume price but cannot see about the snapshot and replication. It would be very helpful to check the price in this docs. Thanks.

**Comment by vickmuir** [comment]
I have forwarded your request to the Offering Managers, Amy Blea and Babatunde Oke. Please allow a few days for an answer, as their response might be delayed due to the holidays.

**Comment by vickmuir** [comment]
Thank you for your patience. I received a response from our Offering Manager. Pricing information for File Storage replicas and Snapshots will be added to https://www.ibm.com/cloud/file-storage/pricing shortly.

**Comment by khayama-zz** [comment]
Have not yet been added... @vickmuir

**Comment by vickmuir** [comment]
Thank you for letting me know. I sent a follow-up note to our Offering Manager (Amy Blea, amyn@us.ibm.com).
