### ISSUE TITLE
documentation needs to include required roles/permissions

### ISSUE THREAD

**Issue by benysh** [ibm-cloud-docs/FileStorage#3]
Our IBMCloud (bluemix) users cannot provision 'File Storage' service.  They get message "You do not have permission to provision this service yet. Contact your team administrator."  but as administrator, I cannot find the info on what is required.

So far the only way I see would be to go into the IaaS (aka 'Classic Infrastructure' aka Softlayer ) permissions and add the authority to the specific user.  However, I'd like to see official documentation on this.  

FWIW, if that is indeed the authorization process, then this is unmanageable for IBM Cloud/bluemix/PaaS.  Might have worked for in softlayer, but in bluemix we use accessgroups for authorizing access to services for dozens of distinct teams over 100's of users.

**Comment by vickmuir** [comment]
Contacted the OM for confirmation.

**Comment by vickmuir** [comment]
The official documentation on Identity and Access Management contains information about the Classic Infrastructure here:  https://cloud.ibm.com/docs/iam?topic=iam-infrapermission

**Comment by benysh** [comment]
I should have been clearer.  "However, I'd like to see official documentation on this"... added to this topic.  Would have saved time if that link was in the docs about the service itself.
