### ISSUE TITLE
Reclaim wait

### ISSUE THREAD

**Issue by gaskinner84** [ibm-cloud-docs/FileStorage#4]
Is it possible that we can specify that these services have a 24 hours reclaim wait period when "immediately" cancelled? Our customers seem to have trouble finding this information in the docs. This info should be true for block and storage devices. 

1) Once devices are canceled, there will be a 24 hour reclaim wait period, then then device data will be destroyed per 

2) You will still see the services in the customer portal after cancellation - once the 24 period has expired, they will be removed from the portal. 

Regards,

Gary S.
ACS-Storage Support Engineer
IBM Cloud Support

**Comment by vickmuir** [comment]
cloud.ibm.com/docs/infrastructure/FileStorage?topic=FileStorage-managingstorage has been updated.
JIRA: https://jira.softlayer.local/browse/DOCS-5514
