### ISSUE TITLE
Unable to see the Replica option

### ISSUE THREAD

**Issue by rashmi-pai** [ibm-cloud-docs/FileStorage#6]
Unable to see the Replica option in the mentioned Navigation. Is this option changed. ?

**Comment by vickmuir** [comment]
Which article are you referring to? It's unclear which option you mean.

**Comment by rashmi-pai** [comment]
Hello,
 
Thanks for looking at this. I was looking at this article (https://cloud.ibm.com/docs/FileStorage?topic=FileStorage-replication)
 
As per this, Navigate to the storage volume and click on replica (screen shot below) . I am not able to see this options in IBM Cloud  Console under Storage > File Storage
 

 
----- Original message -----From: Vicky Muirhead <notifications@github.com>To: ibm-cloud-docs/FileStorage <FileStorage@noreply.github.com>Cc: rashmi-pai <rashmi.pai@in.ibm.com>, Author <author@noreply.github.com>Subject: [EXTERNAL] Re: [ibm-cloud-docs/FileStorage] Unable to see the Replica option (#6)Date: Thu, Feb 20, 2020 9:36 PM 
Which article are you referring to? It's unclear which option you mean.

**Comment by vickmuir** [comment]
The option to **Order Replica** only appears when two conditions are met:
1. Snapshot space is available on the volume.
2. A snapshot schedule is configured.
When the snapshot schedule is set up, you can order a replica volume. I will update the documentation to make this more clear.
